const promptsList = [
  'First person to touch something blue picks someone to drink.',
  'First person to touch something red picks someone to drink.',
  'First person to touch something green picks someone to drink.',
  'First person to touch something yellow picks someone to drink.',
  'First person to touch something orange picks someone to drink.',
  'First person to touch something purple picks someone to drink.',
  'First person to touch something pink picks someone to drink.',
  'Last person to touch the floor drinks.',
  'Last person to touch the wall drinks.',
  'Last person to touch the ceiling drinks.',
  'Last person to touch a phone drinks.',
  'Last person to touch a drink drinks.',
  'Last person to touch another player drinks.',
  'Last person to touch their foot drinks.',
  'Last person to touch their nose drinks.',
  'First person to do 10 pushups picks someone to drink.',
  'First person to do 10 jumping jacks picks someone to drink.',
  'First person to spin around 5 times picks someone to drink.',
  'Last person to clap their hands drinks.',
  'First person to find a coin and show it picks someone to drink.',
  'Last person to say "drink" drinks.',
  'First person to touch something furry picks someone to drink.',
  'First person to recite the alphabet backward picks someone to drink.', // This is a hard one
  'Last person to touch their head drinks.',
  'First person to find a pen picks someone to drink.',
  'Last person to stand up drinks.',
  'First person to touch something cold picks someone to drink.',
  'First person to name three countries starting with "A" picks someone to drink.',
  'Last person to stand on one leg drinks.',
  'First person to touch something with stripes picks someone to drink.',
  'First person to touch something with polka dots picks someone to drink.',
  'Last person to raise their hand drinks.',
  'First person to touch something made of metal picks someone to drink.',
  'First person to touch something made of wood picks someone to drink.',
  'Last person to blink drinks.',
  'First person to touch something with wheels picks someone to drink.',
  'Last person to name a movie drinks.',
  'First person to touch something edible picks someone to drink.',
  'Last person to touch their elbows drinks.',
  'First person to touch something that starts with the letter "S" picks someone to drink.',
  'First person to touch something that starts with the letter "T" picks someone to drink.',
  'First person to touch something that starts with the letter "P" picks someone to drink.',
  'First person to touch something that starts with the letter "M" picks someone to drink.',
  'First person to touch something that starts with the letter "C" picks someone to drink.',
  'First person to touch something that starts with the letter "R" picks someone to drink.',
  'First person to touch something that starts with the letter "B" picks someone to drink.',
  'First person to touch something that starts with the letter "F" picks someone to drink.',
  'First person to touch something that starts with the letter "G" picks someone to drink.',
  'First person to touch something that starts with the letter "H" picks someone to drink.',
  'First person to touch something that starts with the letter "L" picks someone to drink.',
  'First person to touch something that starts with the letter "W" picks someone to drink.',
  'First person to go on their phone and pull up a picture of a cat picks someone to drink.',
  'First person to go on their phone and pull up a picture of a dog picks someone to drink.',
  'First person to go on their phone and pull up a picture of a racoon picks someone to drink.',
  'First person to go on their phone and pull up a picture of a Danny Devito picks someone to drink.',
  'First person to go on their phone and pull up a picture of a Dwayne Johnson holding a rock picks someone to drink.',
  'Last person to name a fruit drinks.',
  'Last person to name a vegetable drinks.',
  'Last person to name a car brand drinks.',
  'Last person to name a book drinks.',
  'Last person to name a color drinks.',
  'Last person to name a planet drinks.',
  'Last person to name a country drinks.',
  'Last person to name a city drinks.',
  'Last person to name a sports team drinks.',
  'First person to name 5 sports teams picks someone to drink.',
  'First person to whistle a tune picks someone to drink.',
  'First person to name five breeds of dogs picks someone to drink.',

  // Add more prompts here
];

export default promptsList;
